function out = model(conditionNumber,relativeMeasurementError,errorAngleDegrees)
%MODEL Transparent two-channel conditioning experiment.
%   OUT = MODEL(CONDITIONNUMBER,RELATIVEMEASUREMENTERROR,ERRORANGLEDEGREES)
%   maps a known two-component parameter state into two measurement
%   channels. One orthogonal state direction has unit gain; the other has
%   gain 1/CONDITIONNUMBER. A bounded measurement perturbation is then
%   inverted analytically in those visible directions. The lesson domain
%   uses either zero error or at least one part per million so tiny storage
%   effects do not compete with the conditioning mechanism in its displays.

if nargin < 1
    conditionNumber = 100;
end
if nargin < 2
    relativeMeasurementError = 0.001;
end
if nargin < 3
    errorAngleDegrees = 90;
end

validateattributes(conditionNumber,{'numeric'}, ...
    {'scalar','real','finite','>=',1,'<=',1e6},mfilename,'conditionNumber');
validateattributes(relativeMeasurementError,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<=',0.01},mfilename,'relativeMeasurementError');
validateattributes(errorAngleDegrees,{'numeric'}, ...
    {'scalar','real','finite','>=',-90,'<=',90},mfilename,'errorAngleDegrees');

minimumNonzeroRelativeMeasurementError = 1e-6;
minimumForInputClass = cast(minimumNonzeroRelativeMeasurementError, ...
    'like',relativeMeasurementError);
if relativeMeasurementError > 0 && ...
        relativeMeasurementError < minimumForInputClass
    error('P03:model:BelowMinimumError', ...
        'relativeMeasurementError must be zero or at least 1e-6 (one ppm).');
end

conditionNumber = double(conditionNumber);
relativeMeasurementError = double(relativeMeasurementError);
errorAngleDegrees = double(errorAngleDegrees);

% Both source components share one unit, and both measurement channels
% share one sensor unit. The sum direction is measured with unit gain; the
% difference direction is measured with gain 1/kappa. Thus the calibrated
% sensor rows become nearly redundant as kappa grows.
stableParameterDirection = [1;1]/sqrt(2);
sensitiveParameterDirection = [1;-1]/sqrt(2);
parameterDirections = [stableParameterDirection sensitiveParameterDirection];
stableMeasurementDirection = stableParameterDirection;
sensitiveMeasurementDirection = sensitiveParameterDirection;

% A = Q*diag([1,1/kappa])*Q'. This explicit 2-by-2 map replaces an opaque
% decomposition: its gains and 2-norm condition number are known by
% construction. Its two rows are the calibrated sensor sensitivities.
systemMatrix = parameterDirections*[1 0;0 1/conditionNumber]*parameterDirections';
trueState = stableParameterDirection;
exactMeasurement = stableMeasurementDirection;

measurementErrorDirection = ...
    cosd(errorAngleDegrees)*stableMeasurementDirection + ...
    sind(errorAngleDegrees)*sensitiveMeasurementDirection;
measurementError = relativeMeasurementError*measurementErrorDirection;
perturbedMeasurement = exactMeasurement + measurementError;

% In the visible sum/difference coordinates, inversion leaves the strong
% component alone and multiplies the weak component by kappa. No generic
% solver, matrix inverse, SVD, or condition estimator is hidden here.
measurementDirectionCoordinates = parameterDirections'*perturbedMeasurement;
estimatedDirectionCoordinates = [measurementDirectionCoordinates(1); ...
    conditionNumber*measurementDirectionCoordinates(2)];
estimatedState = parameterDirections*estimatedDirectionCoordinates;
parameterError = estimatedState-trueState;
parameterErrorCoordinates = parameterDirections'*parameterError;

% Apply the same two visible forward gains to inspect fit to the perturbed
% data. A tiny residual can coexist with a large error from the true state.
predictedMeasurement = systemMatrix*estimatedState;
residual = predictedMeasurement-perturbedMeasurement;

relativeInputError = norm(measurementError)/norm(exactMeasurement);
relativeSolutionError = norm(parameterError)/norm(trueState);
directionalAmplification = sqrt(cosd(errorAngleDegrees)^2 + ...
    conditionNumber^2*sind(errorAngleDegrees)^2);
conditionBound = conditionNumber*relativeInputError;
rowSeparationDegrees = 2*atand(1/conditionNumber);
if norm(perturbedMeasurement)==0
    relativeResidual = 0;
else
    relativeResidual = norm(residual)/norm(perturbedMeasurement);
end

out = struct( ...
    'conditionNumber',conditionNumber, ...
    'relativeMeasurementError',relativeMeasurementError, ...
    'minimumNonzeroRelativeMeasurementError',minimumNonzeroRelativeMeasurementError, ...
    'errorAngleDegrees',errorAngleDegrees, ...
    'systemMatrix',systemMatrix, ...
    'rowSeparationDegrees',rowSeparationDegrees, ...
    'stableParameterDirection',stableParameterDirection, ...
    'sensitiveParameterDirection',sensitiveParameterDirection, ...
    'stableMeasurementDirection',stableMeasurementDirection, ...
    'sensitiveMeasurementDirection',sensitiveMeasurementDirection, ...
    'trueState',trueState, ...
    'exactMeasurement',exactMeasurement, ...
    'measurementErrorDirection',measurementErrorDirection, ...
    'measurementError',measurementError, ...
    'perturbedMeasurement',perturbedMeasurement, ...
    'measurementDirectionCoordinates',measurementDirectionCoordinates, ...
    'estimatedDirectionCoordinates',estimatedDirectionCoordinates, ...
    'parameterErrorCoordinates',parameterErrorCoordinates, ...
    'parameterError',parameterError, ...
    'estimatedState',estimatedState, ...
    'predictedMeasurement',predictedMeasurement, ...
    'residual',residual, ...
    'relativeInputError',relativeInputError, ...
    'relativeSolutionError',relativeSolutionError, ...
    'inputErrorPercent',100*relativeInputError, ...
    'solutionErrorPercent',100*relativeSolutionError, ...
    'directionalAmplification',directionalAmplification, ...
    'conditionBound',conditionBound, ...
    'conditionBoundPercent',100*conditionBound, ...
    'boundUtilization',directionalAmplification/conditionNumber, ...
    'relativeResidual',relativeResidual);
end
