function out = model(startValue,increment,additions)
%MODEL Repeated ordered addition in IEEE-style single precision.
%   OUT = MODEL(STARTVALUE,INCREMENT,ADDITIONS) converts the two numeric
%   inputs to single precision, performs each addition in order, and keeps
%   a double analytical change reference built from those stored inputs.
%   Change coordinates isolate per-operation roundoff without losing a tiny
%   update when it is added to a much larger absolute starting value.

if nargin < 1
    startValue = 1;
end
if nargin < 2
    increment = 3*2^-25;
end
if nargin < 3
    additions = 64;
end

validateattributes(startValue,{'numeric'}, ...
    {'scalar','real','finite','>=',2^-20,'<=',2^20},mfilename,'startValue');
validateattributes(increment,{'numeric'}, ...
    {'scalar','real','finite','>=',0,'<=',2^20},mfilename,'increment');
validateattributes(additions,{'numeric'}, ...
    {'scalar','real','finite','integer','>=',0,'<=',10000},mfilename,'additions');
additions = double(additions);

storedStart = single(startValue);
storedIncrement = single(increment);
storedHistory = zeros(1,additions+1,'single');
storedHistory(1) = storedStart;
for k = 1:additions
    % The explicit dependency makes the rounding location visible. Do not
    % replace this loop with sum or cumsum, which may change grouping.
    storedHistory(k+1) = storedHistory(k) + storedIncrement;
end

step = 0:additions;
storedValue = double(storedHistory);
referenceChange = step*double(storedIncrement);
spacingAtStart = double(eps(storedStart));

stepRoundoff = zeros(1,additions);
cumulativeError = zeros(1,additions+1);
for k = 1:additions
    observedStep = double(storedHistory(k+1))-double(storedHistory(k));
    stepRoundoff(k) = observedStep-double(storedIncrement);
    cumulativeError(k+1) = cumulativeError(k)+stepRoundoff(k);
end
% This sum is a display coordinate. The separate referenceChange and
% cumulativeError fields retain small corrections across the full domain.
observedChangeHistory = referenceChange+cumulativeError;

changedSteps = sum(diff(storedHistory) ~= 0);
if additions == 0
    absorbedFraction = 0;
else
    absorbedFraction = (additions-changedSteps)/additions;
end

expectedChange = referenceChange(end);
observedChange = observedChangeHistory(end);
if expectedChange == 0
    relativeChangeError = 0;
else
    relativeChangeError = cumulativeError(end)/expectedChange;
end

out = struct( ...
    'precision','single', ...
    'requestedStart',double(startValue), ...
    'requestedIncrement',double(increment), ...
    'storedStart',double(storedStart), ...
    'storedIncrement',double(storedIncrement), ...
    'startConversionError',double(storedStart)-double(startValue), ...
    'incrementConversionError',double(storedIncrement)-double(increment), ...
    'additions',additions, ...
    'step',step, ...
    'storedValue',storedValue, ...
    'referenceChange',referenceChange, ...
    'observedChangeHistory',observedChangeHistory, ...
    'cumulativeError',cumulativeError, ...
    'stepRoundoff',stepRoundoff, ...
    'spacingAtStart',spacingAtStart, ...
    'incrementInUlps',double(storedIncrement)/spacingAtStart, ...
    'changedSteps',changedSteps, ...
    'unchangedSteps',additions-changedSteps, ...
    'absorbedFraction',absorbedFraction, ...
    'expectedChange',expectedChange, ...
    'observedChange',observedChange, ...
    'relativeChangeError',relativeChangeError, ...
    'stepwiseFinal',storedValue(end), ...
    'roundedOnceFinal',double(single(double(storedStart)+expectedChange)), ...
    'finalError',cumulativeError(end), ...
    'finalErrorInUlps',cumulativeError(end)/spacingAtStart, ...
    'errorInStartUlps',cumulativeError/spacingAtStart);
end
